### ISSUE TITLE
Failed to download module in the requirement.txt

### ISSUE THREAD

**Issue by qigangdeng** [RADAR-base/radarpipeline#60]
**Describe the bug**

Follow the instruction [listed](https://github.com/RADAR-base/radarpipeline), and run `python .`, it reported: 
`(base) 192:radarpipeline qigangdeng$ python .
Traceback (most recent call last):
  File "/Users/qigangdeng/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/qigangdeng/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 1, in <module>
    from radarpipeline import radarpipeline
  File "./radarpipeline/__init__.py", line 1, in <module>
    from radarpipeline.project import Project
  File "./radarpipeline/project/__init__.py", line 1, in <module>
    from radarpipeline.project.project import Project
  File "./radarpipeline/project/project.py", line 9, in <module>
    from git.exc import GitCommandError
ModuleNotFoundError: No module named 'git'`

-   OS: [macOS]

**Comment by thepushkarp** [comment]
Hey @qigangdeng 

I did a fresh install and it seems to work on my mac machine.

> `git.exc import GitCommandError ModuleNotFoundError: No module named 'git'`

I think its something to do with the [GitPython module](https://github.com/gitpython-developers/GitPython). Can you try manually installing the package and then running again?

```bash
pip install GitPython
```

Let me know what you see.
